### ISSUE TITLE
It cannot transfer a playlist alone.

### ISSUE THREAD

**Issue by sctech-tr** [sigma67/spotify_to_ytmusic#112]
The error is this:

Getting Spotify tracks...
Could not get Spotify playlist. Please check the playlist link.
 Error: TypeError('sequence item 0: expected str instance, NoneType found')
Traceback (most recent call last):
  File "/home/selim/.local/bin/spotify_to_ytmusic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/selim/.local/lib/python3.12/site-packages/spotify_to_ytmusic/main.py", line 98, in main
    args.func(args)
  File "/home/selim/.local/lib/python3.12/site-packages/spotify_to_ytmusic/controllers.py", line 77, in create
    _create_ytmusic(args, playlist, ytmusic)
  File "/home/selim/.local/lib/python3.12/site-packages/spotify_to_ytmusic/controllers.py", line 61, in _create_ytmusic
    name = args.name + date if args.name else playlist["name"] + date
                                              ~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by sigma67** [comment]
duplicate of #104
