### ISSUE TITLE
Am I missing something? got the setup done logged in with google etc.

### ISSUE THREAD

**Issue by Norbii91** [sigma67/spotify_to_ytmusic#113]
C:\Users\norbii\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts>spotify_to_ytmusic create https://open.spotify.com/playlist/0437kD81kWvOcuHrP3vIsS?si=cf7964f8db9b4bba
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\norbii\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\spotify_to_ytmusic.exe\__main__.py", line 7, in <module>
  File "C:\Users\norbii\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spotify_to_ytmusic\main.py", line 98, in main
    args.func(args)
  File "C:\Users\norbii\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spotify_to_ytmusic\controllers.py", line 75, in create
    spotify, ytmusic = _init()
                       ^^^^^^^
  File "C:\Users\norbii\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spotify_to_ytmusic\controllers.py", line 29, in _init
    return Spotify(), YTMusicTransfer()
           ^^^^^^^^^
  File "C:\Users\norbii\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spotify_to_ytmusic\spotify.py", line 27, in __init__
    use_oauth = conf.getboolean("use_oauth")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 1324, in get
    return _impl(self._name, option, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 844, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 824, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 819, in _get
    return conv(self.get(section, option, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 1184, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: y

**Comment by CalciB** [comment]
Similar while using the all command
```
C:\Users\calci> spotify_to_ytmusic all calcib
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\calci\.local\bin\spotify_to_ytmusic.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\calci\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\main.py", line 98, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "C:\Users\calci\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\controllers.py", line 33, in all
    spotify, ytmusic = _init()
                       ~~~~~^^
  File "C:\Users\calci\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\controllers.py", line 29, in _init
    return Spotify(), YTMusicTransfer()
           ~~~~~~~^^
  File "C:\Users\calci\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\spotify.py", line 27, in __init__
    use_oauth = conf.getboolean("use_oauth")
  File "C:\Program Files\Python313\Lib\configparser.py", line 1329, in get
    return _impl(self._name, option, raw=raw, vars=vars,
                 fallback=fallback, **kwargs)
  File "C:\Program Files\Python313\Lib\configparser.py", line 857, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                          raw=raw, vars=vars, fallback=fallback, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\configparser.py", line 837, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     **kwargs)
                     ^^^^^^^^^
  File "C:\Program Files\Python313\Lib\configparser.py", line 832, in _get
    return conv(self.get(section, option, **kwargs))
  File "C:\Program Files\Python313\Lib\configparser.py", line 1202, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: y
```

**Comment by sigma67** [comment]
well i mean it does quite clearly state the options there:

https://github.com/sigma67/spotify_to_ytmusic/blob/8d39c1b1f172aa3985d3954d445466c7e758f34e/spotify_to_ytmusic/setup.py#L64
