### ISSUE TITLE
Getting this weird error. (dont know much about coding)

### ISSUE THREAD

**Issue by RayquazaLearnsToCode** [sigma67/spotify_to_ytmusic#121]
Searching YouTube...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\googles\.local\bin\spotify_to_ytmusic.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\Googles\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\main.py", line 98, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "C:\Users\Googles\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\controllers.py", line 77, in
 create
    _create_ytmusic(args, playlist, ytmusic)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Googles\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\controllers.py", line 63, in
 _create_ytmusic
    videoIds = ytmusic.search_songs(playlist["tracks"])
  File "C:\Users\Googles\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\ytmusic.py", line 35, in search_songs
    result = self.api.search(query)
  File "C:\Users\Googles\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\ytmusicapi\mixins\search.py", line 183, in search
    response = self._send_request(endpoint, body)
  File "C:\Users\Googles\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\ytmusicapi\ytmusic.py", line 241, in _send_request
    raise YTMusicServerError(message + error)
ytmusicapi.exceptions.YTMusicServerError: Server returned HTTP 400: Bad Request.
Request contains an invalid argument.

I did everything exactly as mentioned in the repository.

**Comment by sctech-tr** [comment]
if you used `python3 -m ytmusicapi oauth` it will not work since google removed oauth, use `python3 -m ytmusicapi browser` instead

**Comment by sigma67** [comment]
A new command for browser based setup has already been added in the latest release
