### ISSUE TITLE
Error after running the 'create' command

### ISSUE THREAD

**Issue by Deathzac** [sigma67/spotify_to_ytmusic#125]
### Hi, I am getting this error! Please let me know what I can do to solve this! I have no python experience whatsoever!

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\gaming pc\.local\bin\spotify_to_ytmusic.exe\__main__.py", line 7, in <module>
  File "C:\Users\Gaming PC\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\main.py", line 98, in main
    args.func(args)
  File "C:\Users\Gaming PC\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\controllers.py", line 75, in create
    spotify, ytmusic = _init()
                       ^^^^^^^
  File "C:\Users\Gaming PC\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\controllers.py", line 29, in _init
    return Spotify(), YTMusicTransfer()
           ^^^^^^^^^
  File "C:\Users\Gaming PC\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\spotify.py", line 27, in __init__
    use_oauth = conf.getboolean("use_oauth")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gaming PC\AppData\Local\Programs\Python\Python312\Lib\configparser.py", line 1273, in get
    return _impl(self._name, option, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gaming PC\AppData\Local\Programs\Python\Python312\Lib\configparser.py", line 806, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gaming PC\AppData\Local\Programs\Python\Python312\Lib\configparser.py", line 786, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gaming PC\AppData\Local\Programs\Python\Python312\Lib\configparser.py", line 781, in _get
    return conv(self.get(section, option, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gaming PC\AppData\Local\Programs\Python\Python312\Lib\configparser.py", line 1146, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: y

**Comment by smromain** [comment]
When you were going through the setup, did you use `y` instead of the word `yes` when this question was asked? 
```
Use OAuth method for authorization to transfer private playlists (yes/no):
```

the code seems to be looking for the word `yes` or `no` explicitly, rather than looking for `y` or `n`. if you re-run setup and answer that question explicitly, you should be good.

**Comment by Deathzac** [comment]
Hi, I don't think I used only Y, but it is definitely possible. I also went through and found that the oAuth method is not supported anymore as Google enforced their security on that front.

It needs to be via browser Auth, which actually ended up working very swell.
Thanks for the reply, however!
