### ISSUE TITLE
Transferring liked playlist results in `list index out of range`

### ISSUE THREAD

**Issue by ageisen2000** [sigma67/spotify_to_ytmusic#68]
Here is the dump
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\spotify_to_ytmusic.exe\__main__.py", line 7, in <module>
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spotify_to_ytmusic\main.py", line 86, in main
    args.func(args)
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spotify_to_ytmusic\controllers.py", line 79, in liked
    _create_ytmusic(args, playlist, ytmusic)
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spotify_to_ytmusic\controllers.py", line 60, in _create_ytmusic
    videoIds = ytmusic.search_songs(playlist["tracks"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spotify_to_ytmusic\ytmusic.py", line 32, in search_songs
    result = self.api.search(query)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ytmusicapi\mixins\search.py", line 218, in search
    parse_search_results(results, search_result_types, type, category))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ytmusicapi\parsers\search.py", line 142, in parse_search_results
    return [
           ^
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ytmusicapi\parsers\search.py", line 143, in <listcomp>
    parse_search_result(result[MRLIR], search_result_types, resultType, category)
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ytmusicapi\parsers\search.py", line 80, in parse_search_result
    search_result['name'] = get_item_text(data, 1, 2)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adamg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ytmusicapi\parsers\_utils.py", line 30, in get_item_text
    return column['text']['runs'][run_index]['text']
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by ageisen2000** [comment]
This seems to have happened because I cancelled a previous transfer (`spotify_to_ytmusic create <spotifylink>`). I cancelled this transfer midway. When I re-ran that transfer then tried to move my liked music over it seems to be working now.

**Comment by sigma67** [comment]
Can you identify the specific song that is causing the issue? You can perhaps add a print statement in the source code before each search query. This would actually be an upstream issue with ytmusicapi.

**Comment by ageisen2000** [comment]
As far as I could tell it was never any specific song. It failed at a different spot every time

**Comment by kler** [comment]
I can confirm that the error is present within `ytmusicapi` `1.2.0`.

As visible in the stack trace this comes from `get_item_text()` in `ytmusicapi\parsers\_utils.py`

I tried the migration several times, and failed at different points, so it's not consistent for a certain song for instance.
The error depends on the data returned from Youtube Music, making `ytmusicapi` crash.

### Code analysis
Looking at the variable called `column` in `get_item_text()` in the debugger, it only has the `0`:th index, while the calling function calls it with a hard coded index of `2`:
`search_result['name'] = get_item_text(data, 1, 2)` [_(link to code)_](https://github.com/sigma67/ytmusicapi/blob/6660058a47dc31cefe1c3686067aeef0333c2590/ytmusicapi/parsers/search.py#L80)


![image](https://github.com/sigma67/spotify_to_ytmusic/assets/966132/aec1d72c-7c9a-43d8-8f94-fa6db8d9ca74)


In case it would be acceptable to ignore the missing entry, there is a param called `none_if_absent`, however this is not passed from the caller function,  meaning that the bug itself is actually in the `ytmusicapi`, and not in its utilization in `spotify_to_ytmusic`AFAICT.

I've tried setting `none_if_absent=True` in the caller function `parse_search_result()` line 80, and does indeed make it work, but I have no idea what side effects it has or if I'm breaking some intended behaviour.

I also had a similar error in `parse_menu_playlists()` [_(link to code)_](https://github.com/sigma67/ytmusicapi/blob/6660058a47dc31cefe1c3686067aeef0333c2590/ytmusicapi/parsers/_utils.py#L6)
where it calls `nav()`, which fails in the item called `menu`.
I tried setting `none_if_absent=True` here as well, and it made the playlist creation succeed.

```
...
YouTube tracks: 4550/4612
YouTube tracks: 4560/4612
YouTube tracks: 4570/4612
YouTube tracks: 4580/4612
YouTube tracks: 4590/4612
YouTube tracks: 4600/4612
YouTube tracks: 4610/4612
Success: created playlist 'Discover Weekly Archive' at
https://music.youtube.com/playlist?list=...
```

Side note: Only 4,517 songs where actually created, but there may be duplicates, I don't know...
