### ISSUE TITLE
Issues on mac

### ISSUE THREAD

**Issue by AISLVE** [sigma67/spotify_to_ytmusic#86]
Traceback (most recent call last):
  File "/opt/homebrew/bin/spotify_to_ytmusic", line 5, in <module>
    from spotify_to_ytmusic.main import main
  File "/opt/homebrew/lib/python3.11/site-packages/spotify_to_ytmusic/main.py", line 4, in <module>
    from spotify_to_ytmusic import controllers
  File "/opt/homebrew/lib/python3.11/site-packages/spotify_to_ytmusic/controllers.py", line 4, in <module>
    import spotipy
  File "/opt/homebrew/lib/python3.11/site-packages/spotipy/__init__.py", line 2, in <module>
    from .client import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/spotipy/client.py", line 12, in <module>
    import requests
  File "/opt/homebrew/lib/python3.11/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/opt/homebrew/lib/python3.11/site-packages/requests/utils.py", line 24, in <module>
    from . import certs
  File "/opt/homebrew/lib/python3.11/site-packages/requests/certs.py", line 14, in <module>
    from certifi import where
ImportError: cannot import name 'where' from 'certifi' (unknown location)

everytime I try running the command

**Comment by sigma67** [comment]
try updating requests

https://stackoverflow.com/questions/76755561/importerror-cannot-import-name-where-from-certifi-unknown-location
