### ISSUE TITLE
I CAN'T TRANSFER MY LIKES PLAYLIST OR PLAYLISTS OF MORE THAN 9,000 SONGS

### ISSUE THREAD

**Issue by TheMassterZone** [sigma67/spotify_to_ytmusic#88]
Hi, thanks for reading me.
I am not a professional programmer, it is a hobby, but I have already made transfers of lists with less than 5,000 songs and they are fine.
But with a greater than 9,000 I can not I get this error.
spotify_to_ytmusic all bryanoomar
Traceback (most recent call last):
  File "/home/bd/.local/bin/spotify_to_ytmusic", line 8, in <module>
    sys.exit(main())
  File "/home/bd/.local/lib/python3.10/site-packages/spotify_to_ytmusic/main.py", line 86, in main
    args.func(args)
  File "/home/bd/.local/lib/python3.10/site-packages/spotify_to_ytmusic/controllers.py", line 33, in all
    spotify, ytmusic = _init()
  File "/home/bd/.local/lib/python3.10/site-packages/spotify_to_ytmusic/controllers.py", line 29, in _init
    return Spotify(), YTMusicTransfer()
  File "/home/bd/.local/lib/python3.10/site-packages/spotify_to_ytmusic/spotify.py", line 27, in __init__
    use_oauth = conf.getboolean("use_oauth")
  File "/usr/lib/python3.10/configparser.py", line 1308, in get
    return _impl(self._name, option, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 830, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
  File "/usr/lib/python3.10/configparser.py", line 810, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 805, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.10/configparser.py", line 1168, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: y

I'm using ElementaryOS 7.1, Python 3.10.12
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by sigma67** [comment]
https://github.com/sigma67/spotify_to_ytmusic/issues/78#issuecomment-1934074598
