### ISSUE TITLE
Error: KeyError('album')

### ISSUE THREAD

**Issue by iamflorencejay** [sigma67/spotify_to_ytmusic#95]
I've got an error when I transferring 800+ songs on YT music. How to fix this stuff?

```
Getting` Spotify tracks...
Spotify tracks: 100/845
Spotify tracks: 200/845
Spotify tracks: 300/845
Spotify tracks: 400/845
Spotify tracks: 500/845
Spotify tracks: 595/845
Spotify tracks: 695/845
Could not get Spotify playlist. Please check the playlist link.
 Error: KeyError('album')
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Florence\AppData\Local\Programs\Python\Python312\Scripts\spotify_to_ytmusic.exe\__main__.py", line 7, in <module>
  File "C:\Users\Florence\AppData\Local\Programs\Python\Python312\Lib\site-packages\spotify_to_ytmusic\main.py", line 86, in main
    args.func(args)
  File "C:\Users\Florence\AppData\Local\Programs\Python\Python312\Lib\site-packages\spotify_to_ytmusic\controllers.py", line 71, in create
    _create_ytmusic(args, playlist, ytmusic)
  File "C:\Users\Florence\AppData\Local\Programs\Python\Python312\Lib\site-packages\spotify_to_ytmusic\controllers.py", line 58, in _create_ytmusic
    name = args.name + date if args.name else playlist["name"] + date
                                              ~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by sigma67** [comment]
See error message

``Could not get Spotify playlist. Please check the playlist link.``

**Comment by iamflorencejay** [comment]
> See error message
> 
> `Could not get Spotify playlist. Please check the playlist link.`

The playlist link is good and for some reason. it cannot extract the playlist.

**Comment by sigma67** [comment]
I cannot help without a way to reproduce

**Comment by MatisAgr** [comment]
Same problem here :
```
╰─ $ spotify_to_ytmusic.exe create https://open.spotify.com/playlist/4JBu91UF1cjpyljkLHja27
Getting Spotify tracks...
Spotify tracks: 100/3576
Spotify tracks: 200/3576
Spotify tracks: 300/3576
Spotify tracks: 400/3576
Spotify tracks: 500/3576
Spotify tracks: 600/3576
Spotify tracks: 700/3576
/.../
Spotify tracks: 2999/3576
Spotify tracks: 3099/3576
Spotify tracks: 3199/3576
Spotify tracks: 3299/3576
Spotify tracks: 3399/3576
Spotify tracks: 3499/3576
Could not get Spotify playlist. Please check the playlist link.
 Error: KeyError('album')
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\matis\.local\bin\spotify_to_ytmusic.exe\__main__.py", line 7, in <module>
  File "C:\Users\matis\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\main.py", line 151, in main
    args.func(args)
  File "C:\Users\matis\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\controllers.py", line 80, in create
    _create_ytmusic(args, playlist, ytmusic)
  File "C:\Users\matis\pipx\venvs\spotify-to-ytmusic\Lib\site-packages\spotify_to_ytmusic\controllers.py", line 64, in _create_ytmusic
    name = args.name + date if args.name else playlist["name"] + date
                                              ~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by caveras4** [comment]
I have not reproduced this, so treat the following as a reading of the code rather than a confirmed cause.

The `Could not get Spotify playlist.` line comes from the `try/except` in `controllers._get_spotify_playlist`, which wraps only `Spotify.getSpotifyPlaylist`. Within that call path there is a single unguarded `["album"]` access, in `build_results`:

```python
album_name = album if album else track["album"]["name"]
```

A playlist entry whose track object has no `album` key, or has `album: null`, would raise `KeyError('album')` there and abort the whole fetch. Local files, podcast episodes and unavailable tracks are plausible sources. That would also explain why this is awkward to reproduce: it needs one such entry to be present, so it shows up on large libraries and not on small test playlists. The report here is consistent with that — 845 tracks, crash past the 600 mark — though that is circumstantial.

If that is the cause, skipping unusable entries instead of raising would cover it:

```python
if not track or not track.get("duration_ms") or not track.get("name"):
    continue
album_name = album if album else (track.get("album") or {}).get("name", "")
```

Entries with no duration or title cannot be matched against YouTube anyway.

The same block reads `track["artists"]` and `track["name"]` unguarded, so those have the same exposure if an entry is unusual in more than one way.

The unguarded access is still present on 0.8.0. I am running the above locally without issues, but on my own library, not on data known to trigger the original report.
